CREATE DATABASE IF NOT EXISTS mement;

USE notes;

CREATE TABLE IF NOT EXISTS notes (
  id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title varchar(255) NOT NULL,
  created DATETIME NOT NULL,
  modified DATETIME NOT NULL,
  bodyContent TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;